// Generated by delombok at Mon May 20 05:22:39 JST 2013
package jp.ac.osakau.farseerfc.purano.effect;

import jp.ac.osakau.farseerfc.purano.dep.DepSet;
import jp.ac.osakau.farseerfc.purano.reflect.MethodRep;
import jp.ac.osakau.farseerfc.purano.util.Types;

public class ArgumentEffect extends Effect implements Cloneable {
	private final int argPos;
	
	public ArgumentEffect(int argPos, DepSet deps, MethodRep from) {
		super(deps, from);
		this.argPos = argPos;
	}
	
	@Override
	public Effect clone() {
		return new ArgumentEffect(argPos, getDeps(), getFrom());
	}
	
	@Override
	public String dumpEffect(MethodRep rep, Types table) {
		if (getArgPos() < rep.getMethodNode().localVariables.size()) {
			return String.format("%s:[%s]", rep.getMethodNode().localVariables.get(getArgPos()).name, getDeps().dumpDeps(rep, table));
		} else {
			return String.format("#%d:[%s]", getArgPos(), getDeps().dumpDeps(rep, table));
		}
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ArgumentEffect)) return false;
		final ArgumentEffect other = (ArgumentEffect)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (!super.equals(o)) return false;
		if (this.getArgPos() != other.getArgPos()) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof ArgumentEffect;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + super.hashCode();
		result = result * PRIME + this.getArgPos();
		return result;
	}
	
	@java.lang.SuppressWarnings("all")
	public int getArgPos() {
		return this.argPos;
	}
}