// Generated by delombok at Mon May 20 05:22:39 JST 2013
package jp.ac.osakau.farseerfc.purano.effect;

import jp.ac.osakau.farseerfc.purano.dep.DepSet;
import jp.ac.osakau.farseerfc.purano.reflect.MethodRep;
import jp.ac.osakau.farseerfc.purano.util.Escape;
import jp.ac.osakau.farseerfc.purano.util.Types;
import lombok.Data;

public abstract class Effect implements Cloneable {
	private DepSet deps;
	private MethodRep from;
	
	public Effect(DepSet deps, MethodRep from) {
		
		this.deps = deps;
		this.from = from;
	}
	
	@Override
	public String toString() {
		return this.getClass().getName();
	}
	
	@Override
	public abstract Effect clone();
	
	public Effect duplicate(MethodRep from) {
		Effect cl = clone();
		cl.setFrom(from);
		return cl;
	}
	
	public String dump(MethodRep rep, Types table, String prefix) {
		String className = getClass().getSimpleName();
		className = className.substring(0, className.length() - 6);
		String fromStr = "";
		if (from != null) {
			fromStr = Escape.from(" From " + from.toString(table));
		}
		return String.format("%s@%s(%s)%s", prefix, Escape.annotation(className), Escape.effect(dumpEffect(rep, table)), fromStr);
	}
	
	public String dumpDot() {
		return "";
	}
	
	protected abstract String dumpEffect(MethodRep rep, Types table);
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Effect)) return false;
		final Effect other = (Effect)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$deps = this.getDeps();
		final java.lang.Object other$deps = other.getDeps();
		if (this$deps == null ? other$deps != null : !this$deps.equals(other$deps)) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof Effect;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		final java.lang.Object $deps = this.getDeps();
		result = result * PRIME + ($deps == null ? 0 : $deps.hashCode());
		return result;
	}
	
	@java.lang.SuppressWarnings("all")
	public DepSet getDeps() {
		return this.deps;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setDeps(final DepSet deps) {
		this.deps = deps;
	}
	
	@java.lang.SuppressWarnings("all")
	public MethodRep getFrom() {
		return this.from;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setFrom(final MethodRep from) {
		this.from = from;
	}
}