// Generated by delombok at Mon May 20 05:22:39 JST 2013
package jp.ac.osakau.farseerfc.purano.effect;

import jp.ac.osakau.farseerfc.purano.dep.DepSet;
import jp.ac.osakau.farseerfc.purano.reflect.MethodRep;
import jp.ac.osakau.farseerfc.purano.util.Types;

public class InvokeDynamicEffect extends Effect implements Cloneable {
	
	public InvokeDynamicEffect(DepSet deps, MethodRep from) {
		super(deps, from);
	}
	
	public InvokeDynamicEffect(MethodRep from) {
		super(new DepSet(), from);
	}
	
	@Override
	public Effect clone() {
		return new InvokeDynamicEffect(getDeps(), getFrom());
	}
	
	@Override
	protected String dumpEffect(MethodRep rep, Types table) {
		return "";
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof InvokeDynamicEffect)) return false;
		final InvokeDynamicEffect other = (InvokeDynamicEffect)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (!super.equals(o)) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof InvokeDynamicEffect;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + super.hashCode();
		return result;
	}
}