// Generated by delombok at Mon May 20 05:22:40 JST 2013
package jp.ac.osakau.farseerfc.purano.dep;

import org.objectweb.asm.Type;
import org.objectweb.asm.tree.analysis.Value;

public class DepValue implements Value {
	private final DepSet deps;
	private final Type type;
	
	public DepValue(Type type) {
		
		this.type = type;
		this.deps = new DepSet();
	}
	
	public DepValue(Type type, DepSet deps) {
		
		this.type = type;
		this.deps = new DepSet(deps);
	}
	
	public int getSize() {
		return type == Type.LONG_TYPE || type == Type.DOUBLE_TYPE ? 2 : 1;
	}
	
	public boolean isReference() {
		return type != null && (type.getSort() == Type.OBJECT || type.getSort() == Type.ARRAY);
	}
	
	public boolean isThis() {
		return type.getSort() == Type.OBJECT && deps.getFields().size() == 0 && deps.getStatics().size() == 0 && deps.getLocals().size() == 1 && deps.getLocals().contains(0);
	}
	
	@Override
	public boolean equals(final Object value) {
		if (value == this) {
			return true;
		} else if (value instanceof DepValue) {
			if (type == null) {
				return ((DepValue)value).type == null;
			} else {
				return type.equals(((DepValue)value).type);
			}
		} else {
			return false;
		}
	}
	
	@Override
	public int hashCode() {
		return type == null ? 0 : type.hashCode();
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "DepValue(deps=" + this.getDeps() + ", type=" + this.getType() + ")";
	}
	
	@java.lang.SuppressWarnings("all")
	public DepSet getDeps() {
		return this.deps;
	}
	
	@java.lang.SuppressWarnings("all")
	public Type getType() {
		return this.type;
	}
}