// Generated by delombok at Mon May 20 05:22:39 JST 2013
package jp.ac.osakau.farseerfc.purano.dep;

import jp.ac.osakau.farseerfc.purano.util.Types;

public class FieldDep {
	private final String desc;
	private final String owner;
	private final String name;
	
	public String dump(Types table) {
		return String.format("%s %s.%s", table.desc2full(desc), table.fullClassName(owner), name);
	}
	
	@java.beans.ConstructorProperties({"desc", "owner", "name"})
	@java.lang.SuppressWarnings("all")
	public FieldDep(final String desc, final String owner, final String name) {
		
		this.desc = desc;
		this.owner = owner;
		this.name = name;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getDesc() {
		return this.desc;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getOwner() {
		return this.owner;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof FieldDep)) return false;
		final FieldDep other = (FieldDep)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$desc = this.getDesc();
		final java.lang.Object other$desc = other.getDesc();
		if (this$desc == null ? other$desc != null : !this$desc.equals(other$desc)) return false;
		final java.lang.Object this$owner = this.getOwner();
		final java.lang.Object other$owner = other.getOwner();
		if (this$owner == null ? other$owner != null : !this$owner.equals(other$owner)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof FieldDep;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		final java.lang.Object $desc = this.getDesc();
		result = result * PRIME + ($desc == null ? 0 : $desc.hashCode());
		final java.lang.Object $owner = this.getOwner();
		result = result * PRIME + ($owner == null ? 0 : $owner.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 0 : $name.hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "FieldDep(desc=" + this.getDesc() + ", owner=" + this.getOwner() + ", name=" + this.getName() + ")";
	}
}