// Generated by delombok at Mon May 20 05:22:40 JST 2013
package jp.ac.osakau.farseerfc.purano.visitor;

import java.util.ArrayList;
import java.util.List;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.MethodInsnNode;

public class InvokeDepMethodVisitor extends MethodVisitor implements Opcodes {
	private final List<MethodInsnNode> invokes = new ArrayList<>();
	
	public InvokeDepMethodVisitor() {
		super(Opcodes.ASM4);
	}
	
	@Override
	public void visitMethodInsn(int opcode, String owner, String name, String desc) {
		invokes.add(new MethodInsnNode(opcode, owner, name, desc));
	}
	
	@java.lang.SuppressWarnings("all")
	public List<MethodInsnNode> getInvokes() {
		return this.invokes;
	}
}